//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepakDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailKuis
    {
        public int DetailKuisId { get; set; }
        public Nullable<int> KuisId { get; set; }
        public Nullable<int> SoalId { get; set; }
    
        public virtual Kuis Kuis { get; set; }
        public virtual Soal Soal { get; set; }
    }
}
