//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepakDigital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DigitalPepakEntities : DbContext
    {
        public DigitalPepakEntities()
            : base("name=DigitalPepakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DetailKuis> DetailKuis { get; set; }
        public DbSet<Hanacaraka> Hanacaraka { get; set; }
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<KawruhBasa> KawruhBasa { get; set; }
        public DbSet<Kewan> Kewan { get; set; }
        public DbSet<Kuis> Kuis { get; set; }
        public DbSet<Paramasastra> Paramasastra { get; set; }
        public DbSet<Paribasan> Paribasan { get; set; }
        public DbSet<Parikan> Parikan { get; set; }
        public DbSet<Soal> Soal { get; set; }
        public DbSet<UserDigipak> UserDigipak { get; set; }
        public DbSet<Wayang> Wayang { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetNewDetailKuisId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewDetailKuisId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewHanacarakaId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewHanacarakaId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKategoriId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKategoriId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKawruhBasaId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKawruhBasaId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKewanId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKewanId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKuisId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKuisId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewParamasastraId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewParamasastraId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewParibasanId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewParibasanId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewParikanId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewParikanId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewSoalId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewSoalId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewUserDigipakId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewUserDigipakId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewWayangId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewWayangId");
        }
    }
}
