//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepakDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public Kategori()
        {
            this.Hanacaraka = new HashSet<Hanacaraka>();
            this.KawruhBasa = new HashSet<KawruhBasa>();
            this.Kewan = new HashSet<Kewan>();
            this.Paramasastra = new HashSet<Paramasastra>();
            this.Paribasan = new HashSet<Paribasan>();
            this.Parikan = new HashSet<Parikan>();
            this.Soal = new HashSet<Soal>();
            this.Wayang = new HashSet<Wayang>();
        }
    
        public int KategoriId { get; set; }
        public string Jenis { get; set; }
    
        public virtual ICollection<Hanacaraka> Hanacaraka { get; set; }
        public virtual ICollection<KawruhBasa> KawruhBasa { get; set; }
        public virtual ICollection<Kewan> Kewan { get; set; }
        public virtual ICollection<Paramasastra> Paramasastra { get; set; }
        public virtual ICollection<Paribasan> Paribasan { get; set; }
        public virtual ICollection<Parikan> Parikan { get; set; }
        public virtual ICollection<Soal> Soal { get; set; }
        public virtual ICollection<Wayang> Wayang { get; set; }
    }
}
