//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepakDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kewan
    {
        public int KewanId { get; set; }
        public string JenengKewan { get; set; }
        public string AnakeKewan { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
