//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepakDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuis
    {
        public Kuis()
        {
            this.DetailKuis = new HashSet<DetailKuis>();
        }
    
        public int KuisId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TotalScore { get; set; }
    
        public virtual ICollection<DetailKuis> DetailKuis { get; set; }
        public virtual UserDigipak UserDigipak { get; set; }
    }
}
