//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepakDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soal
    {
        public Soal()
        {
            this.DetailKuis = new HashSet<DetailKuis>();
        }
    
        public int SoalId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ICollection<DetailKuis> DetailKuis { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
